document.addEventListener('DOMContentLoaded', function () {
	// Til parametrlari
	const translations = {
		uz: {
			Asosiy: 'Asosiy',
			'Biz haqimizda': 'Biz haqimizda',
			Taomnoma: 'Taomnoma',
			'Buyurtma qilish': 'Buyurtma qilish',
			Galereya: 'Galereya',
			Aloqa: 'Aloqa',
			"Ro'yhatdan o'tish": "Ro'yhatdan o'tish",
			Kirish: 'Kirish',
			Profil: 'Profil',
			Chiqish: 'Chiqish',
			"An'anaviy ta'm": "An'anaviy ta'm",
			"Eng zo'r Somsa": "Eng zo'r Somsa",
			"Bizning maxsus somsa bilan kuningiz maroqli o'tsin!":
				"Bizning maxsus somsa bilan kuningiz maroqli o'tsin!",
			'Har bir parcha go‘sht o‘z tarixidan hikoya qiluvchi, har bir somsada quvonch uchqunlari bo‘lgan choyxonamizga xush kelibsiz.':
				"Har bir parcha go'sht o'z tarixidan hikoya qiluvchi, har bir somsada quvonch uchqunlari bo'lgan choyxonamizga xush kelibsiz.",
			'Hoziroq buyurtma': 'Hoziroq buyurtma',
			"Biz bilan bog'lanish": "Biz bilan bog'lanish",
			'Xona Buyurtma Qilish': 'Xona Buyurtma Qilish',
			'Mening savatim': 'Mening savatim',
			Jami: 'Jami',
			"Ro'yxatni yuborish": "Ro'yxatni yuborish",
			'Tez yetkazib berish': 'Tez yetkazib berish',
			'Tabiiy mahsulotlar': 'Tabiiy mahsulotlar',
			'Yillik tajriba': 'Yillik tajriba',
			'Biz Haqimizda': 'Biz Haqimizda',
			'Oʻzbek pazandaligida somsa asosan, tandirga yopib dumaloq shaklda tayyorlanadi. Hozir gaz duxovkalarida uchburchak, toʻrtburchak va nonli shaklda ham pishiriladi. Somsa tayyorlash uchun bugʻdoy unidan xamir qorilib, jild tayyorlanadi. Somsaga koʻpincha Sirka, pomidor qaylasi, Jizzax somsasiga esa oʻsimlik moyi sepilib tanovul qilinadi. Jizzax somsasining o‘ziga xos ta’mi qolgan viloyatlardagidan hajmi, go‘sht va dumba yog‘ining mo‘lligi bilan farq qiladi.':
				'Oʻzbek pazandaligida somsa asosan, tandirga yopib dumaloq shaklda tayyorlanadi. Hozir gaz duxovkalarida uchburchak, toʻrtburchak va nonli shaklda ham pishiriladi. Somsa tayyorlash uchun bugʻdoy unidan xamir qorilib, jild tayyorlanadi. Somsaga koʻpincha Sirka, pomidor qaylasi, Jizzax somsasiga esa oʻsimlik moyi sepilib tanovul qilinadi. Jizzax somsasining o‘ziga xos ta’mi qolgan viloyatlardagidan hajmi, go‘sht va dumba yog‘ining mo‘lligi bilan farq qiladi.',
			"An'anaviy taomlar": "An'anaviy taomlar",
			'Qadriyatimizni saqlab qolgan retseptlar':
				'Qadriyatimizni saqlab qolgan retseptlar',
			'Tabiiy mahsulotlar': 'Tabiiy mahsulotlar',
			'Atrofimizdagi fermerlardan sotib olinadi':
				'Atrofimizdagi fermerlardan sotib olinadi',
			'Bizni kuzatib boring': 'Bizni kuzatib boring',
			'Bizning Taomnoma': 'Bizning Taomnoma',
			Somsa: 'Somsa',
			'Sizning energiya darajangizni uch baravar oshiradigan oziq-ovqat':
				'Sizning energiya darajangizni uch baravar oshiradigan oziq-ovqat',
			'Salqin Ichimliklar': 'Salqin Ichimliklar',
			'Sizni sovutish uchun ajoyib va gazli salqin ichimliklar':
				'Sizni sovutish uchun ajoyib va gazli salqin ichimliklar',
			'Salatlar va boshqa narsalar': 'Salatlar va boshqa narsalar',
			'Bizning mazali salatlarimiz siz uchun':
				'Bizning mazali salatlarimiz siz uchun',
			Shashliklar: 'Shashliklar',
			'Sevimli kaboblaringiz hammasi bir joyda':
				'Sevimli kaboblaringiz hammasi bir joyda',
			'Qovurilgan Tovuq': 'Qovurilgan Tovuq',
			"Qovurilgan tovuq go'shtining ajoyib ta'mi":
				"Qovurilgan tovuq go'shtining ajoyib ta'mi",
			Osh: 'Osh',
			"O'zbekistonning ajoyib ta'miga ega milliy taomi":
				"O'zbekistonning ajoyib ta'miga ega milliy taomi",
			'Mening savatim': 'Mening savatim',
			Jami: 'Jami',
			"so'm": "so'm",
			"Ro'yxatni yuborish": "Ro'yxatni yuborish",
			"Buyurtma ma'lumotlari": "Buyurtma ma'lumotlari",
			Ismingiz: 'Ismingiz',
			'Telefon raqam': 'Telefon raqam',
			Manzilingiz: 'Manzilingiz',
			'Izoh (ixtiyoriy)': 'Izoh (ixtiyoriy)',
			Yuborish: 'Yuborish',
			'Xona Buyurtma Qilish': 'Xona Buyurtma Qilish',
			'Zamonaviy va qulay xonalar': 'Zamonaviy va qulay xonalar',
			'Oilaviy tadbirlar, ziyofatlar yoki biznes uchrashuvlari uchun ajoyib joy':
				'Oilaviy tadbirlar, ziyofatlar yoki biznes uchrashuvlari uchun ajoyib joy',
			'Xona band qilish': 'Xona band qilish',
			'Elektron pochta': 'Elektron pochta',
			'Sanani tanlang': 'Sanani tanlang',
			'Vaqtni tanlang': 'Vaqtni tanlang',
			'Mehmonlar soni': 'Mehmonlar soni',
			'Maxsus talablar': 'Maxsus talablar',
			'Xona tanlang': 'Xona tanlang',
			'Xona 1 (2-4 kishi)': 'Xona 1 (2-4 kishi)',
			'Xona 2 (4-6 kishi)': 'Xona 2 (4-6 kishi)',
			'Xona 3 (6-8 kishi)': 'Xona 3 (6-8 kishi)',
			'Xona 4 (8-12 kishi)': 'Xona 4 (8-12 kishi)',
			'VIP Xona (12-20 kishi)': 'VIP Xona (12-20 kishi)',
			"Shaxsiy ma'lumotlaringiz himoya qilinadi":
				"Shaxsiy ma'lumotlaringiz himoya qilinadi",
			'Buyurtma berish': 'Buyurtma berish',
			Galereya: 'Galereya',
			'Xamirturushli xamirdan tayyorlangan mazali somsa':
				'Xamirturushli xamirdan tayyorlangan mazali somsa',
			"Tabiiy go'shtdan tayyorlangan klassik shashlik":
				"Tabiiy go'shtdan tayyorlangan klassik shashlik",
			Tovuq: 'Tovuq',
			'Nozik tandir usulida pishirilgan tovuq':
				'Nozik tandir usulida pishirilgan tovuq',
			"O'zbekistonning mashhur milliy taomi":
				"O'zbekistonning mashhur milliy taomi",
			Jiz: 'Jiz',
			"Qo'y go'shtidan tayyorlangan mazali taom":
				"Qo'y go'shtidan tayyorlangan mazali taom",
			Shorva: 'Shorva',
			'Tabiiy masalliqlardan tayyorlangan issiq shorva':
				'Tabiiy masalliqlardan tayyorlangan issiq shorva',
			'Ismingizni kiriting': 'Ismingizni kiriting',
			'Telefon raqamingizni kiriting': 'Telefon raqamingizni kiriting',
			'Elektron pochta manzilingizni kiriting':
				'Elektron pochta manzilingizni kiriting',
			'Mehmonlar sonini kiriting': 'Mehmonlar sonini kiriting',
			'Xona raqamini': 'Xona raqamini',
			'Maxsus talablar yoki istaklaringizni yozing':
				'Maxsus talablar yoki istaklaringizni yozing',
			"Biz bilan bog'lanish": "Biz bilan bog'lanish",
			'Bizning manzil': 'Bizning manzil',
			'Restoranimizga tashrif buyuring': 'Restoranimizga tashrif buyuring',
			'Humo choyxonasi': 'Humo choyxonasi',
			"Yo'nalish": "Yo'nalish",
			Avtotransport: 'Avtotransport',
			"Shahardan uzoq bo'lmagan masofada joylashgan":
				"Shahardan uzoq bo'lmagan masofada joylashgan",
			'Bepul parkovka': 'Bepul parkovka',
			"30 ta mashina sig'adigan parkovka maydoni":
				"30 ta mashina sig'adigan parkovka maydoni",
			'Jamoat transporti': 'Jamoat transporti',
			'Avtobus bekatidan 5 daqiqalik masofada':
				'Avtobus bekatidan 5 daqiqalik masofada',
			'Ish vaqtlari': 'Ish vaqtlari',
			'Dushanba - Juma': 'Dushanba - Juma',
			Shanba: 'Shanba',
			Yakshanba: 'Yakshanba',
			Yopiq: 'Yopiq',
			'Xabar qoldiring': 'Xabar qoldiring',
			'Xabarni yuborish': 'Xabarni yuborish',
			"Jizzax viloyati, Sharof Rashidov tumani, Qang'li MFY":
				"Jizzax viloyati, Sharof Rashidov tumani, Qang'li MFY",
			'Telefon raqamingiz': 'Telefon raqamingiz',
			'Sizning xabaringiz': 'Sizning xabaringiz',
			Yuborish: 'Yuborish',
			"To'lovlar": "To'lovlar",
			'Onlayn buyurtma qiling': 'Onlayn buyurtma qiling',
			Somsalar: 'Somsalar',
			Ichimliklar: 'Ichimliklar',
			Shashlik: 'Shashlik',
			"Tovuq Go'shti": "Tovuq Go'shti",
			Salatlar: 'Salatlar',
			'Bizni kuzating': 'Bizni kuzating',
			somsalar: 'Somsalar',
			kattaSomsa: 'Katta Somsa',
			priceKattaSomsa: "38 000 so'm",
			kichkinaSomsa: 'Kichkina Somsa',
			priceKichkinaSomsa: "33 000 so'm",
			kosaSomsa: 'Kosa Somsa',
			priceKosaSomsa: "35 000 so'm",
			salatlar: 'Salatlar',
			svejiKatta: 'Sveji Katta',
			priceSvejiKatta: "15 000 so'm",
			svejiKichkina: 'Sveji Kichkina',
			priceSvejiKichkina: "10 000 so'm",
			salyonniy: 'Salyonniy',
			priceSalyonniy: "5 000 so'm",
			mujskoyKapriz: 'Mujskoy Kapriz',
			priceMujskoyKapriz: "20 000 so'm",
			qozikorinSalat: "Qo'ziqorin Salat",
			priceQozikorinSalat: "15 000 so'm",
			non: 'Non',
			priceNon: "5 000 so'm",
			ayron: 'Ayron',
			priceAyron: "5 000 so'm",
			chakki: 'Chakki',
			priceChakki: "5 000 so'm",
			kokChoy: "Ko'k Choy",
			priceKokChoy: "4 000 so'm",
			limonChoy: 'Limon Choy',
			priceLimonChoy: "7 000 so'm",
			'menu-title': 'Oshlar',
			'osh-1-title': 'Osh bir porsiya',
			'osh-1-price': "40 000 so'm",
			'osh-2-title': 'Osh 0.5kg',
			'osh-2-price': "150 000 so'm",
			'osh-3-title': 'Osh 1kg',
			'osh-3-price': "270 000 so'm",
			'menu-title': 'Shashliklar',
			'shashlik-1-title': 'Qiyma shashlik',
			'shashlik-1-price': "38 000 so'm",
			'shashlik-2-title': "Qo'y Kuska",
			'shashlik-2-price': "45 000 so'm",
			'shashlik-3-title': 'Mol Kuska',
			'shashlik-3-price': "42 000 so'm",
			'shashlik-4-title': 'Rulet Shashlik',
			'shashlik-4-price': "34 000 so'm",
			'shashlik-5-title': 'Tovuq Shashlik',
			'shashlik-5-price': "30 000 so'm",
			'shashlik-6-title': 'Assarti Shashlik',
			'shashlik-6-price': "140 000 so'm",
			menuDrinks: 'Ichimliklar',
			cocaCola: 'Coca Cola 1.5 l',
			cocaColaPrice: "17 000 so'm",
			fanta: 'Fanta 1.5 l',
			fantaPrice: "17 000 so'm",
			sprite: 'Sprite 1.5 l',
			spritePrice: "15 000 so'm",
			dena: 'Dena 1 l',
			denaPrice: "14 000 so'm",
			energyDrink: 'Energetik',
			energyDrinkPrice: "10 000 so'm",
			chortoq: 'Chortoq 1 l',
			chortoqPrice: "13 000 so'm",
			menuChicken: 'Qovurilgan Tovuqlar',
			friedChicken: 'Qovurilgan Tovuq',
			friedChickenPrice: "60 000 so'm",
			blyonniy: 'Blyonniy',
			blyonniyPrice: "65 000 so'm",
			grill: 'Gril',
			grillPrice: "55 000 so'm",
			'Tizimga Kirish': 'Tizimga Kirish',
			'Login yoki Email': 'Login yoki Email',
			Parol: 'Parol',
			'Meni eslaysizmi': 'Meni eslaysizmi',
			'Parolni unutdingizmi?': 'Parolni unutdingizmi?',
			Kirish: 'Kirish',
			"Hisobingiz yo'qmi?": "Hisobingiz yo'qmi?",
			"Ro'yxatdan o'tish": "Ro'yxatdan o'tish",
			"Ro'yxatdan O'tish": "Ro'yxatdan O'tish",
			Login: 'Login',
			Ism: 'Ism',
			Email: 'Email',
			Parol: 'Parol',
			'Parolni tasdiqlang': 'Parolni tasdiqlang',
			Kabinet: 'Kabinet',
			Zakazlarim: 'Zakazlarim',
			"Parolni o'zgartish": "Parolni o'zgartish",
			Chiqish: 'Chiqish',
			'Bosh sahifa': 'Bosh sahifa',
			'Zakaz ID': 'Zakaz ID',
			Ism: 'Ism',
			Telefon: 'Telefon',
			Manzil: 'Manzil',
			Izoh: 'Izoh',
			Mahsulotlar: 'Mahsulotlar',
			'Umumiy summa': 'Umumiy summa',
			'Joriy parol': 'Joriy parol',
			'Yangi parol': 'Yangi parol',
			'Yangi parol (takror)': 'Yangi parol (takror)',
			"Parolni o'zgartirish": "Parolni o'zgartirish",
			"Profil ma'lumotlari": "Profil ma'lumotlari",
			Email: 'Email',
			Tahrirlash: 'Tahrirlash',
			Saqlash: 'Saqlash',
			'Bekor qilish': 'Bekor qilish',
			Statistika: 'Statistika',
			'Aktiv tadbirlar': 'Aktiv tadbirlar',
			'Mehmonlar soni': 'Mehmonlar soni',
		},
		ru: {
			Asosiy: 'Главная',
			'Biz haqimizda': 'О нас',
			Taomnoma: 'Меню',
			'Buyurtma qilish': 'Заказать',
			Galereya: 'Галерея',
			Aloqa: 'Контакты',
			"Ro'yhatdan o'tish": 'Регистрация',
			Kirish: 'Вход',
			Profil: 'Профиль',
			Chiqish: 'Выход',
			"An'anaviy ta'm": 'Традиционный вкус',
			"Eng zo'r Somsa": 'Лучшие Самсы',
			"Bizning maxsus somsa bilan kuningiz maroqli o'tsin!":
				'Приятного аппетита с нашей особенной самсой!',
			'Har bir parcha go‘sht o‘z tarixidan hikoya qiluvchi, har bir somsada quvonch uchqunlari bo‘lgan choyxonamizga xush kelibsiz.':
				'Добро пожаловать в нашу чайхану, где каждый кусочек мяса рассказывает свою историю, а каждая самса полна искр радости.',
			'Hoziroq buyurtma': 'Заказать сейчас',
			"Biz bilan bog'lanish": 'Связаться с нами',
			'Xona Buyurtma Qilish': 'Забронировать столик',
			'Mening savatim': 'Моя корзина',
			Jami: 'Итого',
			"Ro'yxatni yuborish": 'Отправить заказ',
			'Tez yetkazib berish': 'Быстрая доставка',
			'Tabiiy mahsulotlar': 'Натуральные продукты',
			'Yillik tajriba': 'Годовой опыт',
			'Biz Haqimizda': 'О нас',
			'Oʻzbek pazandaligida somsa asosan, tandirga yopib dumaloq shaklda tayyorlanadi. Hozir gaz duxovkalarida uchburchak, toʻrtburchak va nonli shaklda ham pishiriladi. Somsa tayyorlash uchun bugʻdoy unidan xamir qorilib, jild tayyorlanadi. Somsaga koʻpincha Sirka, pomidor qaylasi, Jizzax somsasiga esa oʻsimlik moyi sepilib tanovul qilinadi. Jizzax somsasining o‘ziga xos ta’mi qolgan viloyatlardagidan hajmi, go‘sht va dumba yog‘ining mo‘lligi bilan farq qiladi.':
				'В узбекской кухне самсу в основном готовят круглой формы, выпекая в тандыре. В настоящее время их также выпекают в газовых печах в форме треугольного, прямоугольного хлеба и буханки. Для приготовления сомсы замешивают тесто из пшеничной муки и делают обертку. Сомсу часто подают с уксусом и томатным соусом, а джизакскую сомсу — с растительным маслом. Неповторимый вкус джизакской самсы отличается от самсы других регионов своим размером, обилием мяса и жирности.',
			"An'anaviy taomlar": 'Традиционные блюда',
			'Qadriyatimizni saqlab qolgan retseptlar':
				'Рецепты, сохраняющие наше достоинство',
			'Tabiiy mahsulotlar': 'Натуральные продукты',
			'Atrofimizdagi fermerlardan sotib olinadi':
				'Куплено у фермеров вокруг нас',
			'Bizni kuzatib boring': 'Подписывайтесь на нас',
			'Bizning Taomnoma': 'Наше меню',
			Somsa: 'Сомса',
			'Sizning energiya darajangizni uch baravar oshiradigan oziq-ovqat':
				'Продукты, которые увеличивают ваш уровень энергии в три раза.',
			'Salqin Ichimliklar': 'Охлажденные напитки',
			'Sizni sovutish uchun ajoyib va gazli salqin ichimliklar':
				'Прекрасные газированные напитки для охлаждения.',
			'Salatlar va boshqa narsalar': 'Салаты и другие блюда',
			'Bizning mazali salatlarimiz siz uchun': 'Наши вкусные салаты для вас.',
			Shashliklar: 'Шашлыки',
			'Sevimli kaboblaringiz hammasi bir joyda':
				'Все ваши любимые шашлыки в одном месте.',
			'Qovurilgan Tovuq': 'Жареная курица',
			"Qovurilgan tovuq go'shtining ajoyib ta'mi":
				'Отличный вкус жареного куриного мяса.',
			Osh: 'Плов',
			"O'zbekistonning ajoyib ta'miga ega milliy taomi":
				'Национальное блюдо Узбекистана с потрясающим вкусом.',
			'Mening savatim': 'Моя корзина',
			Jami: 'Итого',
			"so'm": 'сом',
			"Ro'yxatni yuborish": 'Отправить заказ',
			"Buyurtma ma'lumotlari": 'Детали заказа',
			Ismingiz: 'Ваше имя',
			'Telefon raqam': 'Номер телефона',
			Manzilingiz: 'Ваш адрес',
			'Izoh (ixtiyoriy)': 'Примечание (необязательно)',
			Yuborish: 'Отправить',
			'Xona Buyurtma Qilish': 'Забронировать столик',
			'Zamonaviy va qulay xonalar': 'Современные и комфортабельные номера',
			'Oilaviy tadbirlar, ziyofatlar yoki biznes uchrashuvlari uchun ajoyib joy':
				'Прекрасное место для семейных мероприятий, вечеринок или деловых встреч.',
			'Xona band qilish': 'Забронировать номер',
			'Elektron pochta': 'Электронная почта',
			'Sanani tanlang': 'Выберите дату',
			'Vaqtni tanlang': 'Выберите время',
			'Mehmonlar soni': 'Количество гостей',
			'Maxsus talablar': 'Особые требования',
			'Xona tanlang': 'Выбрать комнату',
			'Xona 1 (2-4 kishi)': 'Комната 1 (2-4 человека)',
			'Xona 2 (4-6 kishi)': 'Комната 2 (4-6 человек)',
			'Xona 3 (6-8 kishi)': 'Комната 3 (6-8 человек)',
			'Xona 4 (8-12 kishi)': 'Комната 4 (8-12 человек)',
			'VIP Xona (12-20 kishi)': 'VIP-комната (12-20 человек)',
			"Shaxsiy ma'lumotlaringiz himoya qilinadi":
				'Ваши персональные данные защищены.',
			'Buyurtma berish': 'Сделать заказ',
			Galereya: 'Галерея',
			'Xamirturushli xamirdan tayyorlangan mazali somsa':
				'Вкусная самса из дрожжевого теста',
			"Tabiiy go'shtdan tayyorlangan klassik shashlik":
				'Классический шашлык из натурального мяса',
			Tovuq: 'Курица',
			'Nozik tandir usulida pishirilgan tovuq': 'Нежная курица в стиле тандури',
			"O'zbekistonning mashhur milliy taomi":
				'Знаменитое национальное блюдо Узбекистана.',
			Jiz: 'Жиз',
			"Qo'y go'shtidan tayyorlangan mazali taom": 'Вкусное блюдо из баранины',
			Shorva: 'Суп',
			'Tabiiy masalliqlardan tayyorlangan issiq shorva':
				'Горячий суп из натуральных ингредиентов',
			'Ismingizni kiriting': 'Введите ваше имя',
			'Telefon raqamingizni kiriting': 'Введите ваш номер телефона',
			'Elektron pochta manzilingizni kiriting':
				'Введите ваш адрес электронной почты',
			'Mehmonlar sonini kiriting': 'Введите количество гостей',
			'Xona raqamini': 'Введите номер комнаты',
			'Maxsus talablar yoki istaklaringizni yozing':
				'Напишите ваши специальные запросы или пожелания',
			"Biz bilan bog'lanish": 'Свяжитесь с нами',
			'Bizning manzil': 'Наш адрес',
			'Restoranimizga tashrif buyuring': 'Посетите наш ресторан',
			'Humo choyxonasi': 'Ресторан Хумо',
			"Yo'nalish": 'Направление',
			Avtotransport: 'Автомобильный транспорт',
			"Shahardan uzoq bo'lmagan masofada joylashgan":
				'Расположен недалеко от города',
			'Bepul parkovka': 'Бесплатная парковка',
			"30 ta mashina sig'adigan parkovka maydoni": 'Парковка на 30 машин',
			'Jamoat transporti': 'Общественный транспорт',
			'Avtobus bekatidan 5 daqiqalik masofada':
				'5 минут от автобусной остановки',
			'Ish vaqtlari': 'Рабочее время',
			'Dushanba - Juma': 'Понедельник - Пятница',
			Shanba: 'Суббота',
			Yakshanba: 'Воскресенье',
			Yopiq: 'Закрыто',
			'Xabar qoldiring': 'Оставить сообщение',
			'Xabarni yuborish': 'Отправить сообщение',
			"Jizzax viloyati, Sharof Rashidov tumani, Qang'li MFY":
				'Джизакская область, район Шарофа Рашидова, квартал Канъли',
			'Telefon raqamingiz': 'Ваш номер телефона',
			'Sizning xabaringiz': 'Ваше сообщение',
			Yuborish: 'Отправить',
			"To'lovlar": 'Платежи',
			'Onlayn buyurtma qiling': 'Заказать онлайн',
			Somsalar: 'Сомсы',
			Ichimliklar: 'Напитки',
			Shashlik: 'Шашлык',
			"Tovuq Go'shti": 'Куриное Мясо',
			Salatlar: 'Салаты',
			'Bizni kuzating': 'Подписывайтесь на нас',
			Ismingiz: 'Ваше имя',
			'Telefon raqam': 'Номер телефона',
			Manzilingiz: 'Ваш адрес',
			'Izoh (ixtiyoriy)': 'Комментарий (необязательно)',
			somsalar: 'Самсы',
			kattaSomsa: 'Большое Самса',
			priceKattaSomsa: '38 000 сум',
			kichkinaSomsa: 'Малая Самса',
			priceKichkinaSomsa: '33 000 сум',
			kosaSomsa: 'Коса Самса',
			priceKosaSomsa: '35 000 сум',
			salatlar: 'Салаты',
			svejiKatta: 'Свежий Ката',
			priceSvejiKatta: '15 000 сум',
			svejiKichkina: 'Свежий Малая',
			priceSvejiKichkina: '10 000 сум',
			salyonniy: 'Салат Салат',
			priceSalyonniy: '5 000 сум',
			mujskoyKapriz: 'Мужской Каприз',
			priceMujskoyKapriz: '20 000 сум',
			qozikorinSalat: 'Грибной салат',
			priceQozikorinSalat: '15 000 сум',
			non: 'Хлеб',
			priceNon: '5 000 сум',
			ayron: 'Айрон',
			priceAyron: '5 000 сум',
			chakki: 'Чакки',
			priceChakki: '5 000 сум',
			kokChoy: 'Зеленый чай',
			priceKokChoy: '4 000 сум',
			limonChoy: 'Лимонный чай',
			priceLimonChoy: '7 000 сум',
			'menu-title': 'Пловы',
			'osh-1-title': 'Плов одна порция',
			'osh-1-price': '40 000 сум',
			'osh-2-title': 'Плов 0.5кг',
			'osh-2-price': '150 000 сум',
			'osh-3-title': 'Плов 1кг',
			'osh-3-price': '270 000 сум',
			'menu-title': 'Шашлыки',
			'shashlik-1-title': 'Шашлык из фарша',
			'shashlik-1-price': '38 000 сум',
			'shashlik-2-title': 'Кускус из баранины',
			'shashlik-2-price': '45 000 сум',
			'shashlik-3-title': 'Кускус из говядины',
			'shashlik-3-price': '42 000 сум',
			'shashlik-4-title': 'Шашлык Рулет',
			'shashlik-4-price': '34 000 сум',
			'shashlik-5-title': 'Шашлык из курицы',
			'shashlik-5-price': '30 000 сум',
			'shashlik-6-title': 'Шашлык Ассарти',
			'shashlik-6-price': '140 000 сум',
			menuDrinks: 'Напитки',
			cocaCola: 'Coca Cola 1.5 л',
			cocaColaPrice: '17 000 сум',
			fanta: 'Fanta 1.5 л',
			fantaPrice: '17 000 сум',
			sprite: 'Sprite 1.5 л',
			spritePrice: '15 000 сум',
			dena: 'Dena 1 л',
			denaPrice: '14 000 сум',
			energyDrink: 'Энергетик',
			energyDrinkPrice: '10 000 сум',
			chortoq: 'Чортоқ 1 л',
			chortoqPrice: '13 000 сум',
			menuChicken: 'Жареная курица',
			friedChicken: 'Жареная курица',
			friedChickenPrice: '60 000 сум',
			blyonniy: 'Блённый',
			blyonniyPrice: '65 000 сум',
			grill: 'Гриль',
			grillPrice: '55 000 сум',
			'Tizimga Kirish': 'Вход в систему',
			'Login yoki Email': 'Логин или Email',
			Parol: 'Пароль',
			'Meni eslaysizmi': 'Запомнить меня',
			'Parolni unutdingizmi?': 'Забыли пароль?',
			Kirish: 'Войти',
			"Hisobingiz yo'qmi?": 'Нет аккаунта?',
			"Ro'yxatdan o'tish": 'Регистрация',
			"Ro'yxatdan O'tish": 'Регистрация',
			Login: 'Логин',
			Ism: 'Имя',
			Email: 'Электронная почта',
			Parol: 'Пароль',
			'Parolni tasdiqlang': 'Подтвердите пароль',
			Kabinet: 'Кабинет',
			Zakazlarim: 'Мои заказы',
			"Parolni o'zgartish": 'Изменить пароль',
			Chiqish: 'Выход',
			'Bosh sahifa': 'Домашняя страница',
			'Zakaz ID': 'ID заказа',
			Ism: 'Имя',
			Telefon: 'Телефон',
			Manzil: 'Адрес',
			Izoh: 'Комментарий',
			Mahsulotlar: 'Товары',
			'Umumiy summa': 'Общая сумма',
			'Joriy parol': 'Текущий пароль',
			'Yangi parol': 'Новый пароль',
			'Yangi parol (takror)': 'Повторите новый пароль',
			"Parolni o'zgartirish": 'Изменить пароль',
			"Profil ma'lumotlari": 'Данные профиля',
			Email: 'Электронная почта',
			Tahrirlash: 'Редактировать',
			Saqlash: 'Сохранить',
			'Bekor qilish': 'Отмена',
			Statistika: 'Статистика',
			'Aktiv tadbirlar': 'Активные мероприятия',
			'Mehmonlar soni': 'Количество гостей',
		},
		en: {
			Asosiy: 'Home',
			'Biz haqimizda': 'About Us',
			Taomnoma: 'Menu',
			'Buyurtma qilish': 'Order',
			Galereya: 'Gallery',
			Aloqa: 'Contact',
			"Ro'yhatdan o'tish": 'Register',
			Kirish: 'Login',
			Profil: 'Profile',
			Chiqish: 'Logout',
			"An'anaviy ta'm": 'Traditional taste',
			"Eng zo'r Somsa": 'Best Samsa',
			"Bizning maxsus somsa bilan kuningiz maroqli o'tsin!":
				'Enjoy your day with our special samsa!',
			'Har bir parcha go‘sht o‘z tarixidan hikoya qiluvchi, har bir somsada quvonch uchqunlari bo‘lgan choyxonamizga xush kelibsiz.':
				'Welcome to our teahouse where every piece of meat tells its own story, and every samsa is full of sparks of joy.',
			'Hoziroq buyurtma': 'Order Now',
			"Biz bilan bog'lanish": 'Contact Us',
			'Xona Buyurtma Qilish': 'Book a Table',
			'Mening savatim': 'My Cart',
			Jami: 'Total',
			"Ro'yxatni yuborish": 'Submit Order',
			'Tez yetkazib berish': 'Fast delivery',
			'Tabiiy mahsulotlar': 'Natural products',
			'Yillik tajriba': 'Years of experience',
			'Biz Haqimizda': 'About Us',
			'Oʻzbek pazandaligida somsa asosan, tandirga yopib dumaloq shaklda tayyorlanadi. Hozir gaz duxovkalarida uchburchak, toʻrtburchak va nonli shaklda ham pishiriladi. Somsa tayyorlash uchun bugʻdoy unidan xamir qorilib, jild tayyorlanadi. Somsaga koʻpincha Sirka, pomidor qaylasi, Jizzax somsasiga esa oʻsimlik moyi sepilib tanovul qilinadi. Jizzax somsasining o‘ziga xos ta’mi qolgan viloyatlardagidan hajmi, go‘sht va dumba yog‘ining mo‘lligi bilan farq qiladi.':
				'In Uzbek cuisine, samsa is mainly prepared in a round shape, wrapped in a tandoor. Nowadays, it is also cooked in a triangular, rectangular, and bread-shaped shape in gas ovens. To prepare samsa, dough is kneaded from wheat flour and a skin is made. Samsa is often served with vinegar and tomato sauce, and Jizzakh samsa is served with vegetable oil. The unique taste of Jizzakh samsa differs from that of other regions in its size, abundance of meat and butt fat.',
			"An'anaviy taomlar": 'Traditional dishes',
			'Qadriyatimizni saqlab qolgan retseptlar':
				'Recipes that preserve our values',
			'Tabiiy mahsulotlar': 'Natural products',
			'Atrofimizdagi fermerlardan sotib olinadi':
				'Purchased from farmers around us',
			'Bizni kuzatib boring': 'Follow us',
			'Bizning Taomnoma': 'Our Menu',
			Somsa: 'Samsa',
			'Sizning energiya darajangizni uch baravar oshiradigan oziq-ovqat':
				'Food that increases your energy level threefold.',
			'Salqin Ichimliklar': 'Cool Drinks',
			'Sizni sovutish uchun ajoyib va gazli salqin ichimliklar':
				'Amazing and fizzy cool drinks to refresh you.',
			'Salatlar va boshqa narsalar': 'Salads and Other Things',
			'Bizning mazali salatlarimiz siz uchun': 'Our delicious salads for you.',
			Shashliklar: 'Kebabs',
			'Sevimli kaboblaringiz hammasi bir joyda':
				'All your favorite kebabs in one place.',
			'Qovurilgan Tovuq': 'Fried Chicken',
			"Qovurilgan tovuq go'shtining ajoyib ta'mi":
				'The amazing taste of fried chicken meat.',
			Osh: 'Pilaf',
			"O'zbekistonning ajoyib ta'miga ega milliy taomi":
				'A national dish of Uzbekistan with an amazing taste.',
			'Mening savatim': 'My Cart',
			Jami: 'Total',
			"so'm": 'som',
			"Ro'yxatni yuborish": 'Submit Order',
			"Buyurtma ma'lumotlari": 'Order Details',
			Ismingiz: 'Your Name',
			'Telefon raqam': 'Phone Number',
			Manzilingiz: 'Your Address',
			'Izoh (ixtiyoriy)': 'Note (Optional)',
			Yuborish: 'Submit',
			'Xona Buyurtma Qilish': 'Book a Table',
			'Zamonaviy va qulay xonalar': 'Modern and comfortable rooms',
			'Oilaviy tadbirlar, ziyofatlar yoki biznes uchrashuvlari uchun ajoyib joy':
				'A great place for family events, parties or business meetings',
			'Xona band qilish': 'Room reservation',
			'Ismingizni kiriting': 'Enter your name',
			'Telefon raqamingizni kiriting': 'Enter your phone number',
			'Elektron pochta manzilingizni kiriting': 'Enter your email address.',
			'Sanani tanlang': 'Choose Date',
			'Vaqtni tanlang': 'Choose Time',
			'Mehmonlar soni': 'Number of Guests',
			'Maxsus talablar': 'Special Requests',
			'Xona tanlang': 'Choose a room',
			'Xona 1 (2-4 kishi)': 'Room 1 (2-4 people)',
			'Xona 2 (4-6 kishi)': 'Room 2 (4-6 people)',
			'Xona 3 (6-8 kishi)': 'Room 3 (6-8 people)',
			'Xona 4 (8-12 kishi)': 'Room 4 (8-12 people)',
			'VIP Xona (12-20 kishi)': 'VIP Room (12-20 people)',
			"Shaxsiy ma'lumotlaringiz himoya qilinadi":
				'Your personal information is protected.',
			'Buyurtma berish': 'Place Order',
			Galereya: 'Gallery',
			'Xamirturushli xamirdan tayyorlangan mazali somsa':
				'Delicious samsa made from yeast dough',
			"Tabiiy go'shtdan tayyorlangan klassik shashlik":
				'Classic kebab made from natural meat',
			Tovuq: 'Chicken',
			'Nozik tandir usulida pishirilgan tovuq':
				'Delicate tandoori-style chicken',
			"O'zbekistonning mashhur milliy taomi":
				'The famous national dish of Uzbekistan',
			Jiz: 'Jizz',
			"Qo'y go'shtidan tayyorlangan mazali taom":
				'Delicious dish made from mutton',
			Shorva: 'Soup',
			'Tabiiy masalliqlardan tayyorlangan issiq shorva':
				'Hot soup made from natural ingredients',
			'Ismingizni kiriting': 'Enter your name',
			'Telefon raqamingizni kiriting': 'Enter your phone number',
			'Elektron pochta manzilingizni kiriting': 'Enter your email address',
			'Mehmonlar sonini kiriting': 'Enter the number of guests',
			'Xona raqamini': 'Enter room number',
			'Maxsus talablar yoki istaklaringizni yozing':
				'Write your special requests or wishes',
			"Biz bilan bog'lanish": 'Contact Us',
			'Bizning manzil': 'Our address',
			'Restoranimizga tashrif buyuring': 'Visit our restaurant',
			'Humo choyxonasi': 'Humo restaurant',
			"Yo'nalish": 'Direction',
			Avtotransport: 'Motor transport',
			"Shahardan uzoq bo'lmagan masofada joylashgan":
				'Located not far from the city',
			'Bepul parkovka': 'Free parking',
			"30 ta mashina sig'adigan parkovka maydoni": 'Parking space for 30 cars',
			'Jamoat transporti': 'Public transport',
			'Avtobus bekatidan 5 daqiqalik masofada': '5 minutes from the bus stop',
			'Ish vaqtlari': 'Working hours',
			'Dushanba - Juma': 'Monday - Friday',
			Shanba: 'Saturday',
			Yakshanba: 'Sunday',
			Yopiq: 'Closed',
			'Xabar qoldiring': 'Leave a message',
			'Xabarni yuborish': 'Send message',
			"Jizzax viloyati, Sharof Rashidov tumani, Qang'li MFY":
				"Jizzax region, Sharof Rashidov district, Qang'li MFY",
			'Telefon raqamingiz': 'Your phone number',
			'Sizning xabaringiz': 'Your message',
			Yuborish: 'Submit',
			"To'lovlar": 'Payments',
			'Onlayn buyurtma qiling': 'Order online',
			Somsalar: 'Samsa',
			Ichimliklar: 'Drinks',
			Shashlik: 'Kebab',
			"Tovuq Go'shti": 'Chicken Meat',
			Salatlar: 'Salads',
			'Bizni kuzating': 'Follow us',
			Ismingiz: 'Your name',
			'Telefon raqam': 'Phone number',
			Manzilingiz: 'Your address',
			'Izoh (ixtiyoriy)': 'Comment (optional)',
			somsalar: 'Samsa',
			kattaSomsa: 'Large Samsa',
			priceKattaSomsa: '38,000 UZS',
			kichkinaSomsa: 'Small Samsa',
			priceKichkinaSomsa: '33,000 UZS',
			kosaSomsa: 'Bowl Samsa',
			priceKosaSomsa: '35,000 UZS',
			salatlar: 'Salads',
			svejiKatta: 'Fresh Large',
			priceSvejiKatta: '15,000 UZS',
			svejiKichkina: 'Fresh Small',
			priceSvejiKichkina: '10,000 UZS',
			salyonniy: 'Salad',
			priceSalyonniy: '5,000 UZS',
			mujskoyKapriz: "Men's Delight",
			priceMujskoyKapriz: '20,000 UZS',
			qozikorinSalat: 'Mushroom Salad',
			priceQozikorinSalat: '15,000 UZS',
			non: 'Bread',
			priceNon: '5,000 UZS',
			ayron: 'Ayran',
			priceAyron: '5,000 UZS',
			chakki: 'Chakki',
			priceChakki: '5,000 UZS',
			kokChoy: 'Green Tea',
			priceKokChoy: '4,000 UZS',
			limonChoy: 'Lemon Tea',
			priceLimonChoy: '7,000 UZS',
			'menu-title': 'Pilafs',
			'osh-1-title': 'Pilaf one serving',
			'osh-1-price': '40,000 UZS',
			'osh-2-title': 'Pilaf 0.5kg',
			'osh-2-price': '150,000 UZS',
			'osh-3-title': 'Pilaf 1kg',
			'osh-3-price': '270,000 UZS',
			'menu-title': 'Shashliks',
			'shashlik-1-title': 'Minced Meat Shashlik',
			'shashlik-1-price': '38,000 UZS',
			'shashlik-2-title': 'Lamb Kuska',
			'shashlik-2-price': '45,000 UZS',
			'shashlik-3-title': 'Beef Kuska',
			'shashlik-3-price': '42,000 UZS',
			'shashlik-4-title': 'Roll Shashlik',
			'shashlik-4-price': '34,000 UZS',
			'shashlik-5-title': 'Chicken Shashlik',
			'shashlik-5-price': '30,000 UZS',
			'shashlik-6-title': 'Assarti Shashlik',
			'shashlik-6-price': '140,000 UZS',
			menuDrinks: 'Drinks',
			cocaCola: 'Coca Cola 1.5 l',
			cocaColaPrice: '17,000 UZS',
			fanta: 'Fanta 1.5 l',
			fantaPrice: '17,000 UZS',
			sprite: 'Sprite 1.5 l',
			spritePrice: '15,000 UZS',
			dena: 'Dena 1 l',
			denaPrice: '14,000 UZS',
			energyDrink: 'Energy Drink',
			energyDrinkPrice: '10,000 UZS',
			chortoq: 'Chortoq 1 l',
			chortoqPrice: '13,000 UZS',
			menuChicken: 'Fried Chickens',
			friedChicken: 'Fried Chicken',
			friedChickenPrice: '60,000 UZS',
			blyonniy: 'Blyonniy',
			blyonniyPrice: '65,000 UZS',
			grill: 'Grill',
			grillPrice: '55,000 UZS',
			'Tizimga Kirish': 'Login to the System',
			'Login yoki Email': 'Login or Email',
			Parol: 'Password',
			'Meni eslaysizmi': 'Remember me',
			'Parolni unutdingizmi?': 'Forgot password?',
			Kirish: 'Login',
			"Hisobingiz yo'qmi?": "Don't have an account?",
			"Ro'yxatdan o'tish": 'Sign Up',
			"Ro'yxatdan O'tish": 'Sign Up',
			Login: 'Login',
			Ism: 'Name',
			Email: 'Email',
			Parol: 'Password',
			'Parolni tasdiqlang': 'Confirm Password',
			profileTitle: 'Profile Information',
			ordersTab: 'My Orders',
			changePasswordTab: 'Change Password',
			profileName: 'Name',
			profileEmail: 'Email',
			profilePhone: 'Phone',
			profileAddress: 'Address',
			editProfileBtn: 'Edit',
			saveBtn: 'Save',
			cancelBtn: 'Cancel',
			ordersTitle: 'My Orders',
			changePasswordTitle: 'Change Password',
			Kabinet: 'Dashboard',
			Zakazlarim: 'My Orders',
			"Parolni o'zgartish": 'Change Password',
			Chiqish: 'Logout',
			'Bosh sahifa': 'Home page',
			'Zakaz ID': 'Order ID',
			Ism: 'Name',
			Telefon: 'Phone',
			Manzil: 'Address',
			Izoh: 'Comment',
			Mahsulotlar: 'Products',
			'Umumiy summa': 'Total Amount',
			'Joriy parol': 'Current Password',
			'Yangi parol': 'New Password',
			'Yangi parol (takror)': 'Confirm New Password',
			"Parolni o'zgartirish": 'Change Password',
			"Profil ma'lumotlari": 'Profile Information',
			Email: 'Email',
			Tahrirlash: 'Edit',
			Saqlash: 'Save',
			'Bekor qilish': 'Cancel',
			Statistika: 'Statistics',
			'Aktiv tadbirlar': 'Active Events',
			'Mehmonlar soni': 'Number of Guests',
		},
	}

	const languageToggle = document.getElementById('language-toggle')
	const currentLanguage = document.querySelector('.current-language')

	// Boshlang'ich tilni o'rnatish
	let currentLang = localStorage.getItem('language') || 'uz'
	currentLanguage.textContent = currentLang.toUpperCase()

	// Matnlarni yangilash funksiyasi
	function updateTexts(lang) {
		const elements = document.querySelectorAll('[data-translate]')

		elements.forEach(element => {
			const key = element.getAttribute('data-translate')
			if (translations[lang] && translations[lang][key]) {
				element.textContent = translations[lang][key]
			}
		})

		// Placeholderlarni ham tarjima qilish
		const placeholders = document.querySelectorAll(
			'[data-translate-placeholder]'
		)
		placeholders.forEach(el => {
			const key = el.getAttribute('data-translate-placeholder')
			if (translations[lang] && translations[lang][key]) {
				el.placeholder = translations[lang][key]
			}
		})
	}

	// Tilni o'zgartirish funksiyasi
	function changeLanguage(lang) {
		currentLang = lang
		localStorage.setItem('language', lang)
		currentLanguage.textContent = lang.toUpperCase()
		updateTexts(lang)

		// Cart totalni yangilash
		const cartTotal = document.querySelector('.cart-total')
		if (cartTotal) {
			const amount = cartTotal.textContent.replace(/[^\d.,]/g, '').trim()
			cartTotal.textContent = translations[lang]['Jami'] + ' ' + amount
		}
	}

	// Tugma bosilganda tilni o'zgartirish
	languageToggle.addEventListener('click', function () {
		const nextLang =
			currentLang === 'uz' ? 'ru' : currentLang === 'ru' ? 'en' : 'uz'
		changeLanguage(nextLang)
	})

	// Sahifa yuklanganda tilni o'rnatish
	updateTexts(currentLang)
})

document
	.getElementById('language-toggle')
	.addEventListener('click', function () {
		const currentLang = document.querySelector('.current-language')
		const flagIcon = document.querySelector('.flag-icon')

		if (currentLang.textContent === 'UZ') {
			currentLang.textContent = 'RU'
			flagIcon.classList.remove('flag-uz')
			flagIcon.classList.add('flag-ru')
		} else if (currentLang.textContent === 'RU') {
			currentLang.textContent = 'EN'
			flagIcon.classList.remove('flag-ru')
			flagIcon.classList.add('flag-en')
		} else {
			currentLang.textContent = 'UZ'
			flagIcon.classList.remove('flag-en')
			flagIcon.classList.add('flag-uz')
		}

		// Bu yerda tilni o'zgartirish logikasi bo'lishi kerak
		// document.documentElement.lang = currentLang.textContent.toLowerCase();
		// ... boshqa til o'zgarishlari
	})
